"""
Main external statistics fetcher.

Orchestrates profile discovery and platform-specific statistics retrieval.
"""

import json
from pathlib import Path
from typing import Dict, List

from .models import PlatformStats, RetrievalStatus
from .discovery import get_profile_info


# Platform provider mapping
from . import codeforces, leetcode, codechef, hackerearth, hackerrank, geeksforgeeks, atcoder, cses

PROVIDERS = {
    "codeforces": codeforces.fetch_codeforces_stats,
    "leetcode": leetcode.fetch_leetcode_stats,
    "codechef": codechef.fetch_codechef_stats,
    "hackerearth": hackerearth.fetch_hackerearth_stats,
    "hackerrank": hackerrank.fetch_hackerrank_stats,
    "geeksforgeeks": geeksforgeeks.fetch_geeksforgeeks_stats,
    "atcoder": atcoder.fetch_atcoder_stats,
    "cses": cses.fetch_cses_stats,
}


def fetch_all_external_stats(repo_root: Path) -> List[PlatformStats]:
    """
    Fetch statistics for all configured platforms.

    Args:
        repo_root: Path to the repository root

    Returns:
        List of PlatformStats for all platforms
    """
    # Discover profiles from repository
    profile_info = get_profile_info(repo_root)

    results = []

    for platform, info in profile_info.items():
        username = info["username"]
        profile_url = info["profile_url"]

        # Get the provider for this platform
        provider = PROVIDERS.get(platform)

        if provider is None:
            # No provider available
            results.append(
                PlatformStats(
                    platform=platform.capitalize(),
                    username=username,
                    profile_url=profile_url,
                    status=RetrievalStatus.UNCONFIGURED,
                    error=f"No provider available for {platform}",
                    source="none",
                )
            )
        else:
            # Fetch statistics using the provider
            try:
                stats = provider(username, profile_url)
                results.append(stats)
            except Exception as e:
                results.append(
                    PlatformStats(
                        platform=platform.capitalize(),
                        username=username,
                        profile_url=profile_url,
                        status=RetrievalStatus.FAILED,
                        error=f"Provider error: {str(e)}",
                        source="provider",
                    )
                )

    return results


def generate_external_stats_json(results: List[PlatformStats], output_path: Path):
    """
    Generate external-stats.json from platform statistics.

    Args:
        results: List of PlatformStats
        output_path: Path to write the JSON file
    """
    data = [stats.to_dict() for stats in results]

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)


def generate_external_stats_markdown(results: List[PlatformStats], output_path: Path):
    """
    Generate external-stats.md from platform statistics.

    Args:
        results: List of PlatformStats
        output_path: Path to write the Markdown file
    """
    lines = [
        "# External Platform Statistics",
        "",
        "<!--",
        "This file is automatically generated by scripts/external_stats.py.",
        "Do not edit this file manually.",
        "To update external statistics, run: python scripts/external_stats.py",
        "-->",
        "",
        "This file contains statistics from external competitive programming platforms.",
        "These are separate from the repository's actual solution files.",
        "",
        "Last updated: See individual platform timestamps below.",
        "",
    ]

    # Group by status
    successful = [s for s in results if s.status == RetrievalStatus.SUCCESS]
    partial = [s for s in results if s.status == RetrievalStatus.PARTIAL]
    unavailable = [s for s in results if s.status == RetrievalStatus.UNAVAILABLE]
    failed = [s for s in results if s.status == RetrievalStatus.FAILED]

    # Successful platforms with detailed sections
    if successful:
        lines.append("## Successfully Retrieved Statistics")
        lines.append("")

        for stats in successful:
            lines.append(f"### {stats.platform}")
            lines.append("")
            lines.append(f"**Profile**: [{stats.username}]({stats.profile_url})")
            lines.append(f"**Source**: {stats.source}")
            lines.append(f"**Retrieval Method**: {stats.retrieval_method}")
            lines.append(f"**Retrieved At**: {stats.retrieved_at}")
            lines.append("")
            lines.append("**Metrics:**")
            lines.append("")

            if stats.metrics:
                for key, value in stats.metrics.items():
                    if value is not None:
                        lines.append(f"- **{key}**: {value}")
            else:
                lines.append("No metrics available")

            lines.append("")

    # Partial results
    if partial:
        lines.append("## Partial Results")
        lines.append("")
        lines.append("The following platforms returned partial data:")
        lines.append("")

        for stats in partial:
            lines.append(f"- **{stats.platform}**: {stats.error}")
            if stats.metrics:
                lines.append(f"  Available metrics: {', '.join(stats.metrics.keys())}")
        lines.append("")

    # Unavailable platforms
    if unavailable:
        lines.append("## Unavailable Platforms")
        lines.append("")
        lines.append("The following platforms could not retrieve statistics:")
        lines.append("")

        for stats in unavailable:
            lines.append(f"- **{stats.platform}**: {stats.error}")
        lines.append("")

    # Failed platforms
    if failed:
        lines.append("## Failed Retrievals")
        lines.append("")
        lines.append("The following platforms failed during retrieval:")
        lines.append("")

        for stats in failed:
            lines.append(f"- **{stats.platform}**: {stats.error}")
        lines.append("")

    # Status legend
    lines.append("## Status Legend")
    lines.append("")
    lines.append("- **success**: All key statistics successfully retrieved")
    lines.append("- **partial**: Some statistics retrieved, but not all")
    lines.append("- **unavailable**: Platform does not expose public profile statistics")
    lines.append("- **failed**: Error occurred during retrieval")
    lines.append("")

    # Important notes
    lines.append("## Important Notes")
    lines.append("")
    lines.append("- External statistics are retrieved from public profile information.")
    lines.append("- These statistics represent actual progress on external platforms.")
    lines.append("- They are separate from the solution files stored in this repository.")
    lines.append("- Profile URLs are the source of truth for verifiability.")
    lines.append("")
    lines.append("## Repository Statistics")
    lines.append("")
    lines.append("For statistics about the actual files in this repository, see [stats.md](stats.md).")
    lines.append("")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def main():
    """Main entry point for external statistics generation."""
    import sys

    repo_root = Path(__file__).parent.parent.parent
    output_dir = repo_root / "docs" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Check for browser support
    try:
        from .browser_renderer import is_playwright_available
        browser_available = is_playwright_available()
        if not browser_available:
            print("Note: Playwright not installed. Browser rendering unavailable.")
            print("Install with: pip3 install -r requirements.txt")
            print("Then run: playwright install chromium")
            print()
    except ImportError:
        browser_available = False
        print("Note: Browser rendering dependencies not available.")
        print("Install with: pip3 install -r requirements.txt")
        print("Then run: playwright install chromium")
        print()

    print("Discovering profiles from repository...")
    profile_info = get_profile_info(repo_root)
    print(f"Found {len(profile_info)} configured platform(s):")
    for platform, info in profile_info.items():
        print(f"  - {platform.capitalize()}: {info['username']}")

    print("\nFetching external statistics...")
    results = fetch_all_external_stats(repo_root)

    print("\nResults:")
    for stats in results:
        status_emoji = {
            RetrievalStatus.SUCCESS: "✓",
            RetrievalStatus.PARTIAL: "◐",
            RetrievalStatus.UNAVAILABLE: "⊘",
            RetrievalStatus.UNCONFIGURED: "?",
            RetrievalStatus.FAILED: "✗",
        }.get(stats.status, "?")

        print(f"  {status_emoji} {stats.platform}: {stats.status.value}")
        if stats.error:
            print(f"      Error: {stats.error}")
        if stats.metrics:
            print(f"      Metrics: {stats.metrics}")

    # Calculate combined platform-reported solves (not unique problems)
    combined_solved = 0
    for stats in results:
        if stats.status in [RetrievalStatus.SUCCESS, RetrievalStatus.PARTIAL]:
            if stats.metrics and "solved" in stats.metrics and stats.metrics["solved"]:
                combined_solved += stats.metrics["solved"]

    if combined_solved > 0:
        print(f"\nCombined platform-reported solves: {combined_solved}")
        print("(Note: This is a simple sum of platform-reported solves, not a unique problem count)")

    # Generate JSON
    json_path = output_dir / "external-stats.json"
    generate_external_stats_json(results, json_path)
    print(f"\nGenerated: {json_path}")

    # Generate Markdown
    md_path = output_dir / "external-stats.md"
    generate_external_stats_markdown(results, md_path)
    print(f"Generated: {md_path}")

    # Count results by status
    success_count = sum(1 for s in results if s.status == RetrievalStatus.SUCCESS)
    partial_count = sum(1 for s in results if s.status == RetrievalStatus.PARTIAL)
    unavailable_count = sum(1 for s in results if s.status == RetrievalStatus.UNAVAILABLE)
    failed_count = sum(1 for s in results if s.status == RetrievalStatus.FAILED)

    print(f"\nSummary: {success_count} successful, {partial_count} partial, {unavailable_count} unavailable, {failed_count} failed")

    # Exit with non-zero if any failures (but unavailable is acceptable)
    if failed_count > 0:
        sys.exit(1)
    else:
        print("\nExternal statistics generation complete!")
        sys.exit(0)


if __name__ == "__main__":
    main()
