"""
Main external statistics fetcher and report generator.

Orchestrates profile discovery, platform-specific statistics retrieval,
snapshot fallbacks, and generated JSON and Markdown documentation.
"""

import json
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime

from .models import PlatformStats, RetrievalStatus
from .discovery import get_profile_info
from .snapshot_loader import get_snapshot_stats


# Platform provider mapping
from . import codeforces, leetcode, codechef, hackerearth, hackerrank, geeksforgeeks, atcoder, cses

PROVIDERS = {
    "codeforces": codeforces.fetch_codeforces_stats,
    "leetcode": leetcode.fetch_leetcode_stats,
    "codechef": codechef.fetch_codechef_stats,
    "hackerearth": hackerearth.fetch_hackerearth_stats,
    "hackerrank": hackerrank.fetch_hackerrank_stats,
    "geeksforgeeks": geeksforgeeks.fetch_geeksforgeeks_stats,
    "atcoder": atcoder.fetch_atcoder_stats,
    "cses": cses.fetch_cses_stats,
}


def fetch_all_external_stats(repo_root: Path) -> List[PlatformStats]:
    """
    Fetch statistics for all configured platforms discovered in repository.

    Args:
        repo_root: Path to the repository root

    Returns:
        List of PlatformStats for all platforms
    """
    profile_info = get_profile_info(repo_root)
    results = []

    # Desired order for canonical output
    platform_order = ["leetcode", "codeforces", "codechef", "hackerrank", "hackerearth", "geeksforgeeks"]

    # Sort discovered platforms to match canonical order, followed by any others
    ordered_keys = [p for p in platform_order if p in profile_info] + [p for p in profile_info if p not in platform_order]

    for platform in ordered_keys:
        info = profile_info[platform]
        username = info["username"]
        profile_url = info["profile_url"]

        provider = PROVIDERS.get(platform)

        if provider is None:
            results.append(
                PlatformStats(
                    platform=platform.capitalize(),
                    username=username,
                    profile_url=profile_url,
                    status=RetrievalStatus.UNCONFIGURED,
                    error=f"No provider available for {platform}",
                    source="none",
                )
            )
            continue

        try:
            stats = provider(username, profile_url)

            # If live retrieval failed or was unavailable, try snapshot fallback
            if stats.status in [RetrievalStatus.UNAVAILABLE, RetrievalStatus.FAILED]:
                snapshot_stats = get_snapshot_stats(platform, username, profile_url)
                if snapshot_stats:
                    results.append(snapshot_stats)
                else:
                    results.append(stats)
            else:
                # Live retrieval succeeded or was partial.
                # Strictly isolate live metrics: never merge snapshot data into a live record.
                results.append(stats)

        except Exception as e:
            # If provider threw uncaught exception, attempt snapshot fallback
            snapshot_stats = get_snapshot_stats(platform, username, profile_url)
            if snapshot_stats:
                results.append(snapshot_stats)
            else:
                results.append(
                    PlatformStats(
                        platform=platform.capitalize(),
                        username=username,
                        profile_url=profile_url,
                        status=RetrievalStatus.FAILED,
                        error=f"Provider error: {str(e)}",
                        source="provider",
                    )
                )

    return results


def generate_external_stats_json(results: List[PlatformStats], output_path: Path):
    """
    Generate external-stats.json from platform statistics.
    """
    data = [stats.to_dict() for stats in results]
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def generate_external_stats_markdown(results: List[PlatformStats], output_path: Path):
    """
    Generate rich external-stats.md from platform statistics.
    """
    lines = [
        "# 🌐 External Platform Profile Statistics",
        "",
        "<!--",
        "This file is automatically generated by scripts/external_stats.py.",
        "Do not edit this file manually.",
        "To update external statistics, run: python scripts/external_stats.py",
        "-->",
        "",
        "Live and verified statistics from external competitive programming and algorithmic practice platforms.",
        "These metrics represent verified activity across official APIs, public GraphQL endpoints, and structured profiles.",
        "",
        "> [!NOTE]",
        "> External statistics reflect platform-specific activity and are maintained independently from the repository's local solution files.",
        "> Solved counts are reported individually per platform and are not aggregated into a misleading total.",
        "",
        "---",
        "",
        "## 📊 Platform Summary",
        "",
        "| Platform | Handle | Status | Source Type | Method | Key Highlights |",
        "| :--- | :--- | :---: | :---: | :--- | :--- |",
    ]

    for s in results:
        status_badge = {
            RetrievalStatus.SUCCESS: "✅ `success`",
            RetrievalStatus.PARTIAL: "🟡 `partial`",
            RetrievalStatus.UNAVAILABLE: "⚪ `unavailable`",
            RetrievalStatus.UNCONFIGURED: "⚙️ `unconfigured`",
            RetrievalStatus.FAILED: "❌ `failed`",
        }.get(s.status, f"`{s.status.value}`")

        source_type_badge = "🟢 `live`" if s.source_type == "live" else "📸 `snapshot`"
        highlights = _format_platform_highlights(s.platform, s.metrics)

        lines.append(
            f"| **[{s.platform}]({s.profile_url})** | `{s.username}` | {status_badge} | {source_type_badge} | `{s.retrieval_method}` | {highlights} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "## 🔍 Detailed Platform Profiles",
        "",
    ])

    for s in results:
        if s.status in [RetrievalStatus.SUCCESS, RetrievalStatus.PARTIAL]:
            lines.extend(_format_platform_detail_section(s))

    # Unavailable or Failed
    unsuccessful = [s for s in results if s.status in [RetrievalStatus.UNAVAILABLE, RetrievalStatus.FAILED, RetrievalStatus.UNCONFIGURED]]
    if unsuccessful:
        lines.extend([
            "---",
            "",
            "## ⚠️ Unavailable or Unconfigured Platforms",
            "",
        ])
        for s in unsuccessful:
            lines.append(f"- **{s.platform}**: {s.error or 'No public metrics accessible'}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## 📖 Methodology & Data Philosophy",
        "",
        "- **Public Structured Data First**: We query official APIs, public GraphQL endpoints (`leetcode.com/graphql`), and REST APIs (`hackerrank.com/rest/hackers/`) rather than fragile text scraping.",
        "- **Semantic Verification**: Star ratings, percentiles, solved categories, and ranks are mapped directly to their actual schema definitions.",
        "- **Live vs Snapshot Transparency**: Live data is queried directly; verified screenshots are used as immutable baseline snapshots when live endpoints are shielded.",
        "- **No Misleading Solved Sums**: Problem overlaps between platforms prevent calculating a mathematically sound single 'total unique solved' number; platform numbers are kept distinct and verifiable.",
        "- **Repository Separation**: Local repository file statistics (file counts, lines of code, test passes) are tracked separately in [stats.md](stats.md).",
        "",
    ])

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _format_platform_highlights(platform: str, m: Dict[str, Any]) -> str:
    """Return a concise highlight string for the summary table."""
    p = platform.lower()
    if p == "leetcode":
        solved = m.get("solved", "—")
        acc = f"{m['acceptance_rate']}% AC" if "acceptance_rate" in m else ""
        streak = f"{m['streak_days']}d streak" if "streak_days" in m else ""
        parts = [f"**{solved}** solved", acc, streak]
        return ", ".join([p for p in parts if p])
    elif p == "codeforces":
        rating = m.get("rating", "—")
        rank = m.get("rank", "")
        solved = f"{m['solved']} solved" if "solved" in m else ""
        return f"Rating **{rating}** ({rank}), {solved}"
    elif p == "codechef":
        rating = m.get("rating", "—")
        league = m.get("league", "")
        dsa = f"DSA **{m['dsa_rating']}**" if "dsa_rating" in m else ""
        solved = f"{m['solved']} solved" if "solved" in m else ""
        parts = [f"Rating **{rating}**", league, dsa, solved]
        return ", ".join([p for p in parts if p])
    elif p == "hackerrank":
        parts = []
        if "problem_solving_stars" in m:
            parts.append(f"Problem Solving **{m['problem_solving_stars']}★**")
        if "total_stars" in m:
            parts.append(f"**{m['total_stars']}** total stars")
        if "total_challenges_solved" in m:
            parts.append(f"**{m['total_challenges_solved']}** solved")
        return ", ".join(parts) if parts else "Public REST API"
    elif p == "hackerearth":
        parts = []
        if "points" in m:
            pts_val = f"{m['points']:,}" if isinstance(m['points'], int) else f"{m['points']}"
            parts.append(f"**{pts_val}** pts")
        if "solved" in m:
            parts.append(f"**{m['solved']}** solved")
        if "basic_programming_rank" in m:
            parts.append(f"BP #{m['basic_programming_rank']}")
        return ", ".join(parts) if parts else "Public Profile"
    elif p == "geeksforgeeks":
        score = f"Score **{m.get('coding_score', '—')}**"
        solved = f"**{m.get('solved', '—')}** solved"
        streak = f"{m.get('longest_streak_days', '—')}d streak" if "longest_streak_days" in m else ""
        return f"{score}, {solved}, {streak}"
    return "Active Profile"


def _format_platform_detail_section(s: PlatformStats) -> List[str]:
    """Generate detailed Markdown section for a specific platform."""
    lines = [
        f"### {s.platform}",
        "",
        f"- **Profile**: [{s.username}]({s.profile_url})",
        f"- **Source**: `{s.source}` (`{s.source_type}`)",
        f"- **Retrieval Method**: `{s.retrieval_method}`",
        f"- **Last Verified**: `{s.retrieved_at}`",
        "",
    ]

    m = s.metrics
    p = s.platform.lower()

    if p == "leetcode":
        lines.extend([
            "#### 🧩 Problem Solving Breakdown",
            "",
            "| Category | Solved |",
            "| :--- | :---: |",
            f"| 🟢 **Easy** | `{m.get('easy', '—')}` |",
            f"| 🟡 **Medium** | `{m.get('medium', '—')}` |",
            f"| 🔴 **Hard** | `{m.get('hard', '—')}` |",
            f"| 🏆 **Total Solved** | **`{m.get('solved', '—')}`** |",
            "",
            "#### 📈 Profile Metrics",
            "",
            f"- **Global Rank**: `#{m.get('global_rank', '—'):,}`" if isinstance(m.get('global_rank'), int) else f"- **Global Rank**: `#{m.get('global_rank', '—')}`",
            f"- **Submissions**: `{m.get('submissions', '—')}` ({m.get('ac_submissions', '—')} accepted)",
            f"- **Acceptance Rate**: `{m.get('acceptance_rate', '—')}%`",
            f"- **Current Streak**: `{m.get('streak_days', '—')} days`",
            f"- **Total Active Days**: `{m.get('total_active_days', '—')} days`",
            f"- **Active Badge**: `{m.get('active_badge', '—')}`",
            "",
        ])
        if "languages" in m and m["languages"]:
            lines.extend([
                "#### 💻 Language Breakdown",
                "",
                "| Language | Problems Solved |",
                "| :--- | :---: |",
            ])
            for lang, count in m["languages"].items():
                lines.append(f"| {lang} | `{count}` |")
            lines.append("")

        if "badges" in m and m["badges"]:
            lines.extend([
                "#### 🎖️ Earned Badges",
                "",
            ])
            for b in m["badges"]:
                lines.append(f"- 🏅 {b}")
            lines.append("")

    elif p == "codeforces":
        lines.extend([
            "#### ⚡ Competitive Rating & Solves",
            "",
            f"- **Current Rating**: `{m.get('rating', '—')}` ({m.get('rank', '—')})",
            f"- **Maximum Rating**: `{m.get('max_rating', '—')}` ({m.get('max_rank', '—')})",
            f"- **Unique Problems Solved**: `{m.get('solved', '—')}`",
            "",
        ])

    elif p == "codechef":
        lines.extend([
            "#### 👨‍🍳 Contest Ratings & Solves",
            "",
            f"- **Current Rating**: `{m.get('rating', '—')}` (★ `{m.get('stars', '—')}` Stars)",
            f"- **Peak Rating**: `{m.get('max_rating', '—')}`",
            f"- **Current League**: `{m.get('league', '—')}`",
            f"- **Global Rank**: `#{m.get('global_rank', '—'):,}`" if isinstance(m.get('global_rank'), int) else f"- **Global Rank**: `#{m.get('global_rank', '—')}`",
            f"- **DSA Monday Rating**: `{m.get('dsa_rating', '—')}` (Rank `#{m.get('dsa_global_rank', '—')}`)",
            f"- **Total Problems Solved**: `{m.get('solved', '—')}`",
            "",
        ])

    elif p == "hackerrank":
        lines.extend([
            "#### 🎖️ Verified Skill Badges",
            "",
            "| Skill Track | Star Level | Solved | Points | Rank |",
            "| :--- | :---: | :---: | :---: | :---: |",
        ])
        badges_dict = m.get("skill_badges", {})
        for name, bdata in badges_dict.items():
            stars_str = f"{'★' * bdata.get('stars', 0)} ({bdata.get('stars', 0)} Stars)" if bdata.get('stars') else "—"
            rank_str = f"#{bdata.get('rank'):,}" if bdata.get('rank') else "—"
            pts_str = f"{bdata.get('points'):,}" if bdata.get('points') is not None else "—"
            lines.append(f"| **{name}** | {stars_str} | `{bdata.get('solved', '—')}` | {pts_str} | {rank_str} |")
        lines.extend([
            "",
            f"- **Total Stars Earned**: `{m.get('total_stars', '—')}`",
            f"- **Total Challenges Solved**: `{m.get('total_challenges_solved', '—')}`",
            "",
        ])
        if "verified_skills" in m and m["verified_skills"]:
            lines.extend([
                "#### 📜 Verified Skills",
                "",
                ", ".join([f"`{sk}`" for sk in m["verified_skills"]]),
                "",
            ])

    elif p == "hackerearth":
        he_lines = [
            "#### 🚀 Competitive Practice & Rankings",
            "",
            f"- **Total Points**: `{m.get('points', '—'):,}`" if isinstance(m.get('points'), int) else f"- **Total Points**: `{m.get('points', '—')}`",
            f"- **Problems Solved**: `{m.get('solved', '—')}`",
            f"- **Solutions Submitted**: `{m.get('submissions', '—')}`",
        ]
        if "basic_programming_rank" in m:
            he_lines.append(f"- **Basic Programming Rank**: `#{m['basic_programming_rank']}`")
        if "algorithms_rank" in m:
            he_lines.append(f"- **Algorithms Rank**: `#{m['algorithms_rank']}`")
        if "top_percentiles" in m and m["top_percentiles"]:
            he_lines.append(f"- **Top Percentiles**: {', '.join(m['top_percentiles'])}")
        he_lines.append("")

        if "badges" in m and m["badges"]:
            he_lines.extend([
                "#### 🎖️ Badges & Achievements",
                "",
            ])
            for b in m["badges"]:
                he_lines.append(f"- 🏅 {b}")
            he_lines.append("")

        streak_parts = []
        if "practice_streak_days" in m:
            streak_parts.append(f"Practice Streak: `{m['practice_streak_days']} days`")
        if "daily_streak_days" in m:
            streak_parts.append(f"Daily Streak: `{m['daily_streak_days']} days`")
        if streak_parts:
            he_lines.extend([
                "#### 🔥 Streaks",
                "",
                f"- {', '.join(streak_parts)}",
                "",
            ])
        lines.extend(he_lines)

    elif p == "geeksforgeeks":
        lines.extend([
            "#### 🎯 Problem Solving & Practice",
            "",
            f"- **Coding Score**: `{m.get('coding_score', '—')}`",
            f"- **Total Problems Solved**: `{m.get('solved', '—')}`",
            f"- **POTDs Solved / Streak**: `{m.get('potd_solved', '—')}` ({m.get('longest_streak_days', '—')} day longest streak)",
            f"- **Current Year Submissions (2026)**: `{m.get('submissions_2026', '—')}` ({m.get('active_days_2026', '—')} active days)",
            "",
            "#### 🧩 Difficulty Breakdown",
            "",
            "| Difficulty | Solved |",
            "| :--- | :---: |",
            f"| 🟢 **Basic** | `{m.get('basic_solved', '—')}` |",
            f"| 🟢 **Easy** | `{m.get('easy_solved', '—')}` |",
            f"| 🟡 **Medium** | `{m.get('medium_solved', '—')}` |",
            f"| 🔴 **Hard** | `{m.get('hard_solved', '—')}` |",
            "",
        ])

    else:
        for k, v in m.items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")

    return lines


def update_readme_external_stats(results: List[PlatformStats], readme_path: Path):
    """
    Update the External Platform Statistics section in README.md from external-stats results.
    """
    if not readme_path.exists():
        return

    content = readme_path.read_text(encoding="utf-8")

    section_lines = [
        "<!-- START_EXTERNAL_STATS -->",
        "### External Platform Statistics",
        "",
        "Public profile statistics from external competitive programming platforms (verified from public APIs, GraphQL, and structured profiles):",
        "",
        "| Platform | Profile | Status | Solves / Rating | Key Highlights |",
        "| :--- | :--- | :---: | :--- | :--- |",
    ]

    for s in results:
        status_badge = "🟢 `live`" if s.source_type == "live" else "📸 `snapshot`"
        p = s.platform.lower()
        m = s.metrics
        solves_rating = "—"
        highlights = "—"

        if p == "leetcode":
            solves_rating = f"**{m.get('solved', '—')}** solved ({m.get('easy', '—')} E / {m.get('medium', '—')} M / {m.get('hard', '—')} H)"
            lc_parts = []
            if "acceptance_rate" in m:
                lc_parts.append(f"{m['acceptance_rate']}% AC")
            if "global_rank" in m:
                rank_fmt = f"#{m['global_rank']:,}" if isinstance(m['global_rank'], int) else f"#{m['global_rank']}"
                lc_parts.append(rank_fmt)
            if "streak_days" in m:
                lc_parts.append(f"{m['streak_days']}d streak")
            if "badges_count" in m:
                lc_parts.append(f"{m['badges_count']} badges")
            highlights = ", ".join(lc_parts) if lc_parts else "Solved Breakdown"
        elif p == "codeforces":
            solves_rating = f"Rating **{m.get('rating', '—')}** (`{m.get('rank', '—')}`), **{m.get('solved', '—')}** solved"
            highlights = f"Max rating {m.get('max_rating', '—')}, Official API verified"
        elif p == "codechef":
            rank_fmt = f"#{m['dsa_global_rank']:,}" if isinstance(m.get('dsa_global_rank'), int) else f"#{m.get('dsa_global_rank', '—')}"
            solves_rating = f"Rating **{m.get('rating', '—')}** (★ {m.get('stars', '—')} Star), **{m.get('solved', '—')}** solved"
            highlights = f"{m.get('league', '—')}, DSA Monday **{m.get('dsa_rating', '—')}** (Rank {rank_fmt})"
        elif p == "hackerrank":
            solves_rating = f"**{m.get('total_stars', '—')}** stars, **{m.get('total_challenges_solved', '—')}** solved"
            hr_parts = []
            if "problem_solving_stars" in m:
                ps_str = f"Problem Solving {m['problem_solving_stars']}★"
                if "problem_solving_rank" in m:
                    ps_str += f" (#{m['problem_solving_rank']:,})"
                hr_parts.append(ps_str)
            if "sql_stars" in m:
                sql_str = f"SQL {m['sql_stars']}★"
                if "sql_rank" in m:
                    sql_str += f" (#{m['sql_rank']:,})"
                hr_parts.append(sql_str)
            lang_stars = []
            for lang in ["cpp", "java", "python"]:
                if f"{lang}_stars" in m:
                    lang_name = "C++" if lang == "cpp" else lang.capitalize()
                    lang_stars.append(f"{lang_name} {m[f'{lang}_stars']}★")
            if lang_stars:
                hr_parts.append("/".join(lang_stars))
            highlights = ", ".join(hr_parts) if hr_parts else "Public REST API verified"
        elif p == "hackerearth":
            pts_fmt = f"{m['points']:,}" if isinstance(m.get('points'), int) else f"{m.get('points', '—')}"
            solves_rating = f"**{pts_fmt}** pts, **{m.get('solved', '—')}** solved ({m.get('submissions', '—')} subs)"
            he_parts = []
            if "basic_programming_rank" in m:
                he_parts.append(f"BP #{m['basic_programming_rank']}")
            if "algorithms_rank" in m:
                he_parts.append(f"Algo #{m['algorithms_rank']}")
            if "top_percentiles" in m and m["top_percentiles"]:
                he_parts.append(", ".join(m["top_percentiles"]))
            if "badges_count" in m:
                he_parts.append(f"{m['badges_count']} badges")
            highlights = ", ".join(he_parts) if he_parts else "Public API verified"
        elif p == "geeksforgeeks":
            solves_rating = f"Score **{m.get('coding_score', '—')}**, **{m.get('solved', '—')}** solved"
            highlights = f"{m.get('potd_solved', '—')} POTDs solved, {m.get('longest_streak_days', '—')}d streak, {m.get('submissions_2026', '—')} subs (2026)"

        section_lines.append(
            f"| **[{s.platform}]({s.profile_url})** | `@{s.username}` | {status_badge} | {solves_rating} | {highlights} |"
        )

    section_lines.extend([
        "",
        "<details>",
        "<summary><b>Detailed Platform Breakdown & Honors</b></summary>",
        "",
    ])

    for s in results:
        p = s.platform.lower()
        m = s.metrics
        if p == "leetcode":
            lang_str = ", ".join([f"{k} (`{v}`)" for k, v in m.get("languages", {}).items()]) if "languages" in m else "—"
            badges_str = ", ".join(m.get("badges", [])[:6]) if "badges" in m else "—"
            rank_fmt = f"#{m['global_rank']:,}" if isinstance(m.get('global_rank'), int) else f"#{m.get('global_rank', '—')}"
            lc_lines = [
                f"#### LeetCode ([@{s.username}]({s.profile_url}))",
                f"- **Problem Solves**: `{m.get('solved', '—')}` total (🟢 Easy: `{m.get('easy', '—')}`, 🟡 Medium: `{m.get('medium', '—')}`, 🔴 Hard: `{m.get('hard', '—')}`)",
            ]
            if "submissions" in m or "ac_submissions" in m or "acceptance_rate" in m:
                lc_lines.append(f"- **Submissions & Acceptance**: `{m.get('submissions', '—')}` submissions, `{m.get('ac_submissions', '—')}` accepted (`{m.get('acceptance_rate', '—')}%` AC rate)")

            streak_parts = []
            if "global_rank" in m:
                streak_parts.append(f"Global Rank `{rank_fmt}`")
            if "streak_days" in m:
                streak_parts.append(f"`{m['streak_days']}` days current streak")
            if "total_active_days" in m:
                streak_parts.append(f"`{m['total_active_days']}` total active days")
            if streak_parts:
                lc_lines.append(f"- **Rankings & Streaks**: {', '.join(streak_parts)}")
            if "languages" in m and m["languages"]:
                lc_lines.append(f"- **Languages**: {lang_str}")
            if "badges" in m and m["badges"]:
                lc_lines.append(f"- **Featured Badges**: {badges_str}")
            lc_lines.append("")
            section_lines.extend(lc_lines)
        elif p == "codeforces":
            section_lines.extend([
                f"#### Codeforces ([@{s.username}]({s.profile_url}))",
                f"- **Current Rating**: `{m.get('rating', '—')}` (`{m.get('rank', '—')}`) | **Max Rating**: `{m.get('max_rating', '—')}` (`{m.get('max_rank', '—')}`)",
                f"- **Unique Solved Problems**: `{m.get('solved', '—')}`",
                "",
            ])
        elif p == "codechef":
            rank_fmt = f"#{m['global_rank']:,}" if isinstance(m.get('global_rank'), int) else f"#{m.get('global_rank', '—')}"
            dsa_rank_fmt = f"#{m['dsa_global_rank']:,}" if isinstance(m.get('dsa_global_rank'), int) else f"#{m.get('dsa_global_rank', '—')}"
            section_lines.extend([
                f"#### CodeChef ([@{s.username}]({s.profile_url}))",
                f"- **Rating**: `{m.get('rating', '—')}` (★ `{m.get('stars', '—')}` Star) | **Max Rating**: `{m.get('max_rating', '—')}` | **League**: `{m.get('league', '—')}`",
                f"- **DSA Monday Rating**: `{m.get('dsa_rating', '—')}` (Rank `{dsa_rank_fmt}`) | **Global Rank**: `{rank_fmt}`",
                f"- **Total Problems Solved**: `{m.get('solved', '—')}`",
                "",
            ])
        elif p == "hackerrank":
            badges_dict = m.get("skill_badges", {})
            badge_items = []
            for name, bdata in badges_dict.items():
                stars = bdata.get("stars", 0)
                stars_txt = f"`{stars}★`" if stars else ""
                rank = bdata.get("rank")
                rank_txt = f", `#{rank:,}`" if rank else ""
                badge_items.append(f"{name} ({stars_txt}{rank_txt})".replace(" ()", ""))
            badges_line = ", ".join(badge_items) if badge_items else "—"

            hr_lines = [
                f"#### HackerRank ([@{s.username}]({s.profile_url}))",
                f"- **Skill Badges**: {badges_line}",
                f"- **Total Stars & Solves**: `{m.get('total_stars', '—')}` stars earned, `{m.get('total_challenges_solved', '—')}` challenges solved",
            ]
            if "verified_skills" in m and m["verified_skills"]:
                skills_str = ", ".join([f"`{sk}`" for sk in m["verified_skills"]])
                hr_lines.append(f"- **Verified Skills**: {skills_str}")
            hr_lines.append("")
            section_lines.extend(hr_lines)
        elif p == "hackerearth":
            pts_fmt = f"{m['points']:,}" if isinstance(m.get('points'), int) else f"{m.get('points', '—')}"
            he_lines = [
                f"#### HackerEarth ([@{s.username}]({s.profile_url}))",
                f"- **Points & Solves**: `{pts_fmt}` points, `{m.get('solved', '—')}` solved, `{m.get('submissions', '—')}` solutions submitted",
            ]
            rank_parts = []
            if "basic_programming_rank" in m:
                rank_parts.append(f"Basic Programming `#{m['basic_programming_rank']}`")
            if "algorithms_rank" in m:
                rank_parts.append(f"Algorithms `#{m['algorithms_rank']}`")
            if rank_parts:
                he_lines.append(f"- **Track Rankings**: {', '.join(rank_parts)}")
            if "top_percentiles" in m and m["top_percentiles"]:
                he_lines.append(f"- **Top Percentiles**: {', '.join(m['top_percentiles'])}")
            if "badges" in m and m["badges"]:
                badges_str = ", ".join(m["badges"])
                he_lines.append(f"- **Badges**: {badges_str}")
            streak_parts = []
            if "practice_streak_days" in m:
                streak_parts.append(f"Practice Streak: `{m['practice_streak_days']}` days")
            if "daily_streak_days" in m:
                streak_parts.append(f"Daily Streak: `{m['daily_streak_days']}` days")
            if streak_parts:
                he_lines.append(f"- **Streaks**: {', '.join(streak_parts)}")
            he_lines.append("")
            section_lines.extend(he_lines)
        elif p == "geeksforgeeks":
            diff_parts = []
            for diff_name in ["basic", "easy", "medium", "hard"]:
                if f"{diff_name}_solved" in m:
                    diff_parts.append(f"{diff_name.capitalize()}: `{m[f'{diff_name}_solved']}`")
            diff_str = f" ({', '.join(diff_parts)})" if diff_parts else ""

            gfg_lines = [
                f"#### GeeksforGeeks ([@{s.username}]({s.profile_url}))",
                f"- **Coding Score**: `{m.get('coding_score', '—')}` | **Total Solved**: `{m.get('solved', '—')}`{diff_str}",
            ]
            streak_parts = []
            if "potd_solved" in m:
                streak_parts.append(f"`{m['potd_solved']}` POTDs solved")
            if "longest_streak_days" in m:
                streak_parts.append(f"`{m['longest_streak_days']}` day longest streak")
            if streak_parts:
                gfg_lines.append(f"- **Streaks & POTD**: {', '.join(streak_parts)}")
            if "submissions_2026" in m:
                act_str = f" across `{m['active_days_2026']}` active days" if "active_days_2026" in m else ""
                gfg_lines.append(f"- **2026 Activity**: `{m['submissions_2026']}` submissions{act_str}")
            gfg_lines.append("")
            section_lines.extend(gfg_lines)

    section_lines.extend([
        "</details>",
        "",
        "See [docs/generated/external-stats.md](docs/generated/external-stats.md) for complete external platform statistics with retrieved metrics, retrieval methods, and timestamps.",
        "",
        "> [!NOTE]",
        "> External platform statistics represent actual progress on external accounts and are tracked independently from the solution files stored in this repository. Solved counts are maintained separately and not combined into a misleading total.",
        "<!-- END_EXTERNAL_STATS -->",
    ])

    new_block = "\n".join(section_lines)

    import re
    if "<!-- START_EXTERNAL_STATS -->" in content and "<!-- END_EXTERNAL_STATS -->" in content:
        updated_content = re.sub(
            r"<!-- START_EXTERNAL_STATS -->.*?<!-- END_EXTERNAL_STATS -->",
            new_block,
            content,
            flags=re.DOTALL,
        )
    else:
        pattern = r"### External Platform Statistics\n.*?(?=\n## Automation)"
        updated_content = re.sub(pattern, new_block + "\n\n", content, flags=re.DOTALL)

    readme_path.write_text(updated_content, encoding="utf-8")


def main():
    """Main entry point for external statistics generation."""
    import sys

    repo_root = Path(__file__).parent.parent.parent
    output_dir = repo_root / "docs" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    print("Discovering profiles from repository...")
    profile_info = get_profile_info(repo_root)
    print(f"Found {len(profile_info)} configured platform(s):")
    for platform, info in profile_info.items():
        print(f"  - {platform.capitalize()}: {info['username']} ({info['profile_url']})")

    print("\nFetching external statistics from public endpoints...")
    results = fetch_all_external_stats(repo_root)

    print("\nResults:")
    for stats in results:
        status_emoji = {
            RetrievalStatus.SUCCESS: "✓",
            RetrievalStatus.PARTIAL: "◐",
            RetrievalStatus.UNAVAILABLE: "⊘",
            RetrievalStatus.UNCONFIGURED: "?",
            RetrievalStatus.FAILED: "✗",
        }.get(stats.status, "?")

        source_label = f"[{stats.source_type}]"
        print(f"  {status_emoji} {stats.platform} {source_label}: {stats.status.value} (method: {stats.retrieval_method})")
        if stats.error:
            print(f"      Error: {stats.error}")
        if stats.metrics:
            key_summary = {k: v for k, v in list(stats.metrics.items())[:6]}
            print(f"      Sample Metrics: {key_summary}")

    # Generate JSON
    json_path = output_dir / "external-stats.json"
    generate_external_stats_json(results, json_path)
    print(f"\nGenerated: {json_path}")

    # Generate Markdown
    md_path = output_dir / "external-stats.md"
    generate_external_stats_markdown(results, md_path)
    print(f"Generated: {md_path}")

    # Update README
    readme_path = repo_root / "README.md"
    update_readme_external_stats(results, readme_path)
    print(f"Updated README: {readme_path}")

    # Count results by status
    success_count = sum(1 for s in results if s.status == RetrievalStatus.SUCCESS)
    partial_count = sum(1 for s in results if s.status == RetrievalStatus.PARTIAL)
    unavailable_count = sum(1 for s in results if s.status == RetrievalStatus.UNAVAILABLE)
    failed_count = sum(1 for s in results if s.status == RetrievalStatus.FAILED)

    print(f"\nSummary: {success_count} successful, {partial_count} partial, {unavailable_count} unavailable, {failed_count} failed")

    if failed_count > 0:
        sys.exit(1)
    else:
        print("\nExternal statistics generation complete!")
        sys.exit(0)


if __name__ == "__main__":
    main()
